import Footer from "./components/Footer";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function getServerSideProps() {
  try {
    const { data } = await axios.get(`${process.env.NEXT_PUBLIC_BASE_URL}/api/google-trends`, {
      params: { geo: 'ID', timestamp: Math.floor(Date.now() / 1000) },
    });

    return {
      props: {
        data: data.data || [], // Data yang diambil dari API
      },
    };
  } catch (error) {
    console.error('Error fetching data:', error.message);
    return {
      props: {
        data: [], // Atau error handling yang sesuai
      },
    };
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
        <link rel="shortcut icon" href="/images/fav.png" type="image/x-icon"></link>
        <link rel="stylesheet preload" href="/css/plugins/fontawesome-5.css" as="style"></link>
        <link rel="stylesheet preload" href="/css/vendor/bootstrap.min.css" as="style"></link>
        <link rel="stylesheet preload" href="/css/vendor/swiper.css" as="style"></link>
        <link rel="stylesheet preload" href="/css/vendor/metismenu.css" as="style"></link>
        <link rel="stylesheet preload" href="/css/vendor/magnific-popup.css" as="style"></link>
        <link rel="stylesheet preload" href="/css/style.css" as="style"></link>
        <body className="home-one">
        <Header />
        <Sidebar />

        {children}
        <Footer />
        </body>
    </html>
  );
}
